In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False

In [4]:
download_data=pd.read_csv('data2/download.csv').sort_values(by='user_id')
download_data

        user_id  model_id          model_type                  created_at
117460        1      6306         Music::Song  2021-07-19 11:11:17.969786
388068        1      2275  Music::SoundEffect  2022-05-12 15:34:11.590195
388065        1      3610  Music::SoundEffect  2022-05-12 15:32:22.402502
37597         1        33   Classify::Package  2021-04-27 10:42:37.279877
388063        1      2275  Music::SoundEffect   2022-05-12 15:30:37.88848
...         ...       ...                 ...                         ...
530202   118129      6524         Music::Song  2022-10-12 17:28:25.388174
530201   118129      6524         Music::Song  2022-10-12 17:28:09.207646
530209   118129      6265         Music::Song  2022-10-12 17:32:01.641734
530206   118130      6221         Music::Song  2022-10-12 17:30:17.285158
530212   118130      6200         Music::Song  2022-10-12 17:32:18.375574

[530213 rows x 4 columns]

In [5]:
user_model_pivot=pd.pivot_table(download_data,index='user_id',columns='model_id',values='created_at',aggfunc='count').fillna(0)
user_model_pivot

model_id,1,2,3,4,5,6,7,8,9,10,...,9448,9450,9452,9454,9456,9458,9460,9462,9464,9466
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
82,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
118126,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
118128,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
118129,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
118130,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
model_user_pivot=pd.pivot_table(download_data,index='model_id',columns='user_id',values='created_at',aggfunc='count').fillna(0)
model_user_pivot

user_id,1,12,29,30,82,161,336,347,350,360,...,118119,118120,118121,118122,118123,118125,118126,118128,118129,118130
model_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9458,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9460,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9462,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9464,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9466,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
from sklearn.metrics.pairwise import cosine_similarity

df_similarity=pd.DataFrame(
    data=cosine_similarity(model_user_pivot,model_user_pivot),
    index=model_user_pivot.index,
    columns=model_user_pivot.index)
df_similarity

model_id,1,2,3,4,5,6,7,8,9,10,...,9448,9450,9452,9454,9456,9458,9460,9462,9464,9466
model_id,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.208792,0.159938,0.233640,0.166886,0.106067,0.218700,0.079015,0.014914,0.098220,...,0.000000,0.000000,0.00000,0.042182,0.000000,0.0,0.000000,0.0,0.0,0.000000
2,0.208792,1.000000,0.249615,0.326377,0.326377,0.165100,0.391463,0.092717,0.050000,0.153670,...,0.070711,0.070711,0.00000,0.070711,0.000000,0.0,0.000000,0.0,0.0,0.000000
3,0.159938,0.249615,1.000000,0.241388,0.232767,0.140894,0.310207,0.012245,0.023113,0.162363,...,0.000000,0.065372,0.00000,0.065372,0.000000,0.0,0.065372,0.0,0.0,0.000000
4,0.233640,0.326377,0.241388,1.000000,0.321739,0.153957,0.341864,0.123513,0.069938,0.153534,...,0.000000,0.000000,0.00000,0.065938,0.000000,0.0,0.000000,0.0,0.0,0.000000
5,0.166886,0.326377,0.232767,0.321739,1.000000,0.142114,0.365041,0.172919,0.023313,0.266125,...,0.000000,0.000000,0.09325,0.065938,0.000000,0.0,0.000000,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9458,0.000000,0.000000,0.000000,0.000000,0.000000,0.127000,0.000000,0.000000,0.000000,0.000000,...,0.707107,0.000000,0.00000,0.000000,0.000000,1.0,0.000000,0.5,0.0,0.000000
9460,0.000000,0.000000,0.065372,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.500000,0.00000,0.000000,0.707107,0.0,1.000000,0.0,0.0,0.707107
9462,0.000000,0.000000,0.000000,0.000000,0.000000,0.063500,0.000000,0.000000,0.000000,0.000000,...,0.353553,0.000000,0.00000,0.353553,0.000000,0.5,0.000000,1.0,0.0,0.000000
9464,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000,0.0,1.0,0.000000
9466,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,1.000000,0.0,0.707107,0.0,0.0,1.000000

In [8]:
def recommand_item_based_CF(id):
    return df_similarity[id].sort_values(ascending=False)[1:6]

recommand_item_based_CF(64)

model_id
63      0.340777
60      0.217061
1160    0.158114
289     0.111803
1167    0.091287
Name: 64, dtype: float64

In [9]:
from sklearn.decomposition import TruncatedSVD

SVD=TruncatedSVD(n_components=16)
matrix=SVD.fit_transform(model_user_pivot)
matrix

array([[ 2.29195726e+00, -1.00892400e+00,  1.88622990e-02, ...,
         9.09455848e-01,  3.42108713e-01,  2.91513944e-01],
       [ 8.85277007e-01,  1.16253130e-01,  3.70758484e-01, ...,
         3.82307798e-01,  8.78875943e-02,  1.45871619e-01],
       [ 7.40080148e-01, -6.05028315e-01, -1.19043414e-01, ...,
         2.46064293e-01,  3.58450189e-02, -1.84924094e-01],
       ...,
       [ 7.11351052e-02, -1.24263476e-02,  1.02369715e-02, ...,
         2.91567630e-02, -2.51085131e-03,  5.65008949e-02],
       [ 1.15109991e-02, -2.92657705e-03, -6.24987462e-04, ...,
         9.56529861e-03, -9.75435831e-04,  4.64764672e-03],
       [ 2.68399011e-02, -2.01816907e-03, -3.38598831e-03, ...,
         1.20412474e-02,  2.41398448e-02, -2.49363793e-03]])

In [10]:
import numpy as np
corr=np.corrcoef(matrix)
corr.shape

(7899, 7899)

In [11]:
model_id=user_model_pivot.columns
df_corr=pd.DataFrame(data=corr,index=model_id,columns=model_id)
df_corr

model_id,1,2,3,4,5,6,7,8,9,10,...,9448,9450,9452,9454,9456,9458,9460,9462,9464,9466
model_id,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.855302,0.842237,0.842252,0.854402,0.527432,0.811321,0.818485,0.635772,0.511923,...,0.099650,0.291920,0.105300,0.212909,0.522826,0.010177,0.530092,0.492655,0.541238,0.522826
2,0.855302,1.000000,0.580597,0.977324,0.962950,0.685410,0.927731,0.916109,0.818378,0.691072,...,0.206239,0.369285,0.055460,0.302895,0.540317,0.105095,0.522930,0.540775,0.600850,0.540317
3,0.842237,0.580597,1.000000,0.524936,0.580988,0.590946,0.566616,0.467575,0.411106,0.499172,...,0.306654,0.408558,0.029891,0.366337,0.391139,0.237399,0.386156,0.401500,0.307946,0.391139
4,0.842252,0.977324,0.524936,1.000000,0.971530,0.578460,0.881334,0.956951,0.826863,0.635156,...,0.162856,0.345053,0.094048,0.276185,0.481314,0.061605,0.485872,0.540792,0.589816,0.481314
5,0.854402,0.962950,0.580988,0.971530,1.000000,0.563132,0.869410,0.939489,0.869384,0.714988,...,0.112791,0.321691,0.170911,0.236630,0.461761,-0.014700,0.466250,0.479274,0.473391,0.461761
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9458,0.010177,0.105095,0.237399,0.061605,-0.014700,0.640239,0.222064,-0.069922,-0.126101,0.406279,...,0.975874,0.808244,-0.279932,0.858169,0.174611,1.000000,0.132232,0.335205,0.149778,0.174611
9460,0.530092,0.522930,0.386156,0.485872,0.466250,0.525987,0.704127,0.412626,0.087359,0.213445,...,0.183180,0.474862,0.310974,0.496376,0.947936,0.132232,1.000000,0.372556,0.547500,0.947936
9462,0.492655,0.540775,0.401500,0.540792,0.479274,0.563286,0.601134,0.322726,0.242172,0.422129,...,0.353312,0.583092,0.442851,0.440019,0.187037,0.335205,0.372556,1.000000,0.736421,0.187037
9464,0.541238,0.600850,0.307946,0.589816,0.473391,0.506444,0.710784,0.437572,0.155166,0.231970,...,0.136764,0.273015,0.191771,0.335663,0.499046,0.149778,0.547500,0.736421,1.000000,0.499046
9466,0.522826,0.540317,0.391139,0.481314,0.461761,0.568422,0.713652,0.439068,0.125599,0.271550,...,0.229029,0.405412,0.118971,0.510717,1.000000,0.174611,0.947936,0.187037,0.499046,1.000000

In [12]:
def recommand_item_based_LF(id):
    return df_corr[id].sort_values(ascending=False)[1:6]

recommand_item_based_LF(64)

model_id
680     0.934804
854     0.934632
2610    0.927759
790     0.926743
2663    0.926250
Name: 64, dtype: float64